#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $KEA_STORK_DB_USER WITH PASSWORD '$KEA_STORK_DB_USER_PASSWORD';
	CREATE DATABASE $KEA_STORK_DB;
	GRANT ALL PRIVILEGES ON DATABASE $KEA_STORK_DB TO $KEA_STORK_DB_USER;
        \connect $KEA_STORK_DB
	create extension pgcrypto;
EOSQL
