---
- name: Create stork-net docker network
  include_role:
    name: kea-stork
    tasks_from: stork-net

- name: copy container environment file
  template:
    src: kea-api_env-file.j2
    dest: /root/kea-api_env
    owner: root
    group: root
    mode: 0400

- name: create Kea dir on host
  file:
    path: /var/lib/kea-api_container
    state: directory
    owner: root
    group: root
    mode: 0550

- name: run Kea container
  community.docker.docker_container:
    name: kea-api
    hostname: kea-api
    container_default_behavior: compatibility
    image: docker/infra-eng/kea-api:{{ kea_docker_tag }}
    pull: true
    state: started
    restart_policy: on-failure
    restart_retries: 2
    network_mode: bridge
    networks:
      - name: stork-net
    memory: 4G
    env_file: /root/kea-api_env
    keep_volumes: yes
    mounts:
      - source: /dev/log
        target: /dev/log
        type: bind
      - source: /var/lib/kea-dhcp_container/kea
        target: /var/kea
        type: bind
      - source: /var/lib/kea-dhcp_container/log
        target: /var/log
        type: bind

- name: remove Kea container environment file
  file:
    path: /root/kea-api_env
    state: absent
